from ECMWFModelTaskClass import ECMWFModelTaskBase


class JMAModel(ECMWFModelTaskBase):
    """
    Tasks for the JMA Models downloaded from ECMWF
    """
    DefaultDelay = 3
    
    def __init__(self, start=None):
        """
        :param start: datetime day to get data (today-DefaultDelay if None)
        """
        super().__init__(JMAModel.DefaultDelay, start)

        pf_toplevel = f"{self.S2S_toplevel}/JMA/REL/PF"
        cf_toplevel = f"{self.S2S_toplevel}/JMA/REL/CF"

        y_m_d = f"{self.start.year}-{self.start.month:02d}-{self.start.day:02d}"
        ymd = f"{self.start.year}{self.start.month:02d}{self.start.day:02d}"

        self.all_models["JMA_REL_CF"] = [
            {
                "target": f"{cf_toplevel}/jma_rel_cf_pl_zuvt{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "130/131/132/156",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "cf",
                "expect": "any",
            },
            {
                "target": f"{cf_toplevel}/jma_rel_cf_pl_q{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "133",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "cf",
                "expect": "any",
            },
            {
                "target": f"{cf_toplevel}/jma_rel_cf_pl_w{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "135",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "cf",
                "expect": "any",
            },
            {
                "target": f"{cf_toplevel}/jma_rel_cf_sfc_sfc{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "121/122/134/146/147/151/165/166/169/172/175/176/177/179/180/181/228002/228143/228228",
                "step": "12/to/816/by/12",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "cf",
                "expect": "any",
            },
            {
                "target": f"{cf_toplevel}/jma_rel_cf_sfc_sfc6_{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "121/122",
                "step": "6/to/804/by/6",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "cf",
                "expect": "any",
            },
            {
                "target": f"{cf_toplevel}/jma_rel_cf_sfc_sfc62_{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "165/166/228228",
                "step": "6/to/804/by/6",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "cf",
                "expect": "any",
            },

            {
                "target": f"{cf_toplevel}/jma_rel_cf_da_sfc{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "31/34/136/167/168/235/228141/228164",
                "step": "0-24/24-48/48-72/72-96/96-120/120-144/144-168/168-192/192-216/216-240/240-264/264-288/288-312/312-336/336-360/360-384/384-408/408-432/432-456/456-480/480-504/504-528/528-552/552-576/576-600/600-624/624-648/648-672/672-696/696-720/720-744/744-768/768-792/792-816",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "cf",
                "expect": "any",
            }
        ]
        self.all_models["JMA_REL_PF"] = [
            {
                "target": f"{pf_toplevel}/jma_rel_pf_pl_zuvt{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "130/131/132/156",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_pl_z{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "156",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_pl_t{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "130",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_pl_u{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "131",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_pl_v{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "132",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },

            {
                "target": f"{pf_toplevel}/jma_rel_pf_pl_q{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "133",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_pl_w{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levelist": "10/50/100/200/300/500/700/850/925/1000",
                "levtype": "pl",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "135",
                "step": "24/to/816/by/24",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_sfc_sfc{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "121/122/134/146/147/151/165/166/169/175/176/177/179/180/181/228143/228228",
                "step": "12/to/816/by/12",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_sfc_sfc6_{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "121/122",
                "step": "6/to/804/by/6",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },
            {
                "target": f"{pf_toplevel}/jma_rel_pf_sfc_sfc62_{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "165/166/228228",
                "step": "6/to/804/by/6",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            },

            {
                "target": f"{pf_toplevel}/jma_rel_pf_da_sfc{ymd}{ymd}.grb",
                "class": "s2",
                "dataset": "s2s",
                "date": y_m_d,
                "expver": "prod",
                "levtype": "sfc",
                "model": "glob",
                "number": "1/to/4",
                "origin": "rjtd",
                "param": "31/34/136/167/168/235/228141/228164",
                "step": "0-24/24-48/48-72/72-96/96-120/120-144/144-168/168-192/192-216/216-240/240-264/264-288/288-312/312-336/336-360/360-384/384-408/408-432/432-456/456-480/480-504/504-528/528-552/552-576/576-600/600-624/624-648/648-672/672-696/696-720/720-744/744-768/768-792/792-816",
                "stream": "enfo",
                "time": "00:00:00",
                "type": "pf",
                "expect": "any",
            }
        ]
